#!/usr/bin/env php
<?php

use ConventionalChangelog\DefaultCommand;
use Symfony\Component\Console\Application;

// Autoload
$files = [
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php',
];
foreach ($files as $file) {
    if (file_exists($file)) {
        require_once $file;
        break;
    }
}

// Report only fatal errors
error_reporting(2039);

// Command
$command = new DefaultCommand();
$commandName = $command->getName();

// Run application single command
$application = new Application('conventional-changelog', '1.2.0');
$application->add($command);
$application->setDefaultCommand($commandName, true);
$application->run();
